# Generated by Django 3.2 on 2021-04-21 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20210420_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='txt1',
            field=models.TextField(null=True),
        ),
    ]
