# Generated by Django 3.2 on 2021-04-21 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_article_txt1'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='txt2',
            field=models.TextField(null=True),
        ),
    ]
